- name: Install collectd and plugins
  package:
    name:
      - collectd
      - collectd-core
    state: latest
  notify: restart collectd

- name: Deploy Prometheus config
  template:
    src: prometheus.conf.j2
    dest: /etc/collectd.d/prometheus.conf
    owner: root
    group: root
    mode: 0644
  notify: restart collectd

- name: Ensure collectd is running
  systemd:
    name: collectd
    state: started
    enabled: yes