- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install collectd and plugins
  package:
    name:
      - collectd
      - collectd-core
      - write-prometheus
    state: latest
  notify: restart collectd

- name: Ensure /etc/collectd.d directory exists
  file:
    path: /etc/collectd.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy Prometheus config
  template:
    src: prometheus.conf.j2
    dest: /etc/collectd.d/prometheus.conf
    owner: root
    group: root
    mode: 0644
  notify: restart collectd

- name: Ensure collectd is running
  systemd:
    name: collectd
    state: started
    enabled: yes
