- name: Stop collectd service
  systemd:
    name: collectd
    state: stopped
    enabled: no

- name: Remove collectd and plugins
  package:
    name:
      - collectd
      - collectd-core
      - write_prometheus
    state: absent

- name: Remove collectd config files
  file:
    path: /etc/collectd.d/
    state: absent